ecommerce/ecommerce/urls.py
"""Url Configurations."""
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^category/(?P<slug>[\w-]+)/$', 'products.views.category_page', name='category_page'),
    url(r'^all_categories/$', 'products.views.all_categories', name='all_categories'),

    url(r'^category/filter/(?P<category>[\w-]+)/(?P<spec_type_id>[\w-]+)/(?P<spec_value_id>[\w-]+)/$', 'products.views.category_page_filter_products', name='category_page_filter_products'),

    url(r'^products/(?P<slug>[\w-]+)/(?P<id>\d+)/$', 'products.views.single', name='single_product'),
    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),

    url(r'^return_product/(?P<order>\d+)/(?P<id>\d+)/$', 'orders.views.return_product', name='return_product'),


    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),
    url(r'^ajax/update_default_address/$', 'accounts.views.update_default_address', name='update_default_address'),
    url(r'^ajax/add_wish_list/$', 'accounts.views.add_wish_list', name='add_wish_list'),
    url(r'^ajax/remove_from_wishlist/(?P<slug>[\w-]+)/(?P<id>\d+)/$', 'accounts.views.remove_from_wishlist', name='remove_from_wishlist'),
    url(r'^ajax/user_account_info_update$', 'accounts.views.user_account_info_update', name='user_account_info_update'),
    url(r'^ajax/user_personal_info_update$', 'accounts.views.user_personal_info_update', name='user_personal_info_update'),
    url(r'^ajax/get_product_variation_price$', 'products.views.get_product_variation_price', name='get_product_variation_price'),

    # url(r'^blog/', include('blog.urls')),
    # (?p<all_items>,*)
    # (?P<id>\d+)
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    # url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    # url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    # url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    url(r'^accounts/address/$', 'accounts.views.view_user_address', name='view_user_address'),
    url(r'^accounts/wistlist/$', 'accounts.views.view_wist_list', name='view_wist_list'),
    url(r'^accounts/account_settings$', 'accounts.views.account_settings', name='account_settings'),
    # url(r'^accounts/', include('allauth.urls')),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/product_description/models.py
"""T."""
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.
from products.models import Variation

ICON_TYPE = (('Google', 'Google'), ('Font-Awesome', 'Font-Awesome'))


class PdpSpecificationType(models.Model):
    """PdpSpecifications Model."""

    # variation = models.ForeignKey(
    #     Variation,
    #     null=True,
    #     blank=True)

    specification_type = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Specification type',
        help_text='Enter Product Specification type. Example "Brand" ')

    # active = models.BooleanField(
    #     default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.specification_type)


class PdpSpecification(models.Model):
    """PdpSpecifications Model."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    specification_type = models.ForeignKey(
        PdpSpecificationType,
        default="")

    specification_value = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Specification value',
        help_text='Enter Product Specification value. Example "Apple" ')

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)


class PdpDescription(models.Model):
    """PdpDescription Model."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Description',
        help_text='Enter Product Description.')

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)


class PdpKeyFeature(models.Model):
    """PdpKeyFeature Model."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    icon_type = models.CharField(
        max_length=225,
        choices=ICON_TYPE,
        default='Google',
        verbose_name='Icon type',
        help_text='Enter Key Feature Icon Type. Select the option of which you want icons of.')

    icon_class = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        default="",
        verbose_name='Icon Class',
        help_text='Enter Key Feature Icon Class. This is required only if you want Font-Awesome icons')

    title = models.TextField(
        blank=True,
        null=True,
        verbose_name='Key Feature Text',
        help_text='Enter Key Feature Text.')

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)


class PdpPhysicalFeature(models.Model):
    """PdpPhysicalFeature Model."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    key_feature_image = models.ImageField(
        upload_to='product_description/images/physical_feature',
        blank=True,
        null=True,
        verbose_name='Physical Feature Image',
        help_text='Enter Product Physical Feature Image.')

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)


class PdpFeatured(models.Model):
    """PdpFeatured Model."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    featured_image = models.ImageField(
        upload_to='product_description/images/featured',
        blank=True,
        null=True,
        verbose_name='Featured Image',
        help_text='Enter Product Featured Image.')

    header = models.TextField(
        blank=True,
        null=True,
        verbose_name='Featured header',
        help_text='Enter Product Featured Header.')

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Featured description',
        help_text='Enter Product Featured description.')

    order = models.IntegerField(
        blank=True,
        null=True,
        verbose_name='Featured Order',
        help_text='The product featured item will be shown in this order.')

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)

ecommerce/products/models.py
"""Models Class."""
from django.core.urlresolvers import reverse
from django.db import models
import datetime
# from django.db.models.signals import post_save
# Create your models here.


class Category(models.Model):
    """docstring for ClassName."""

    category_name = models.CharField(
        max_length=120,
        null=True,
        blank=True)

    description = models.TextField(
        null=True,
        blank=True)

    slug = models.SlugField(
        unique=True,
        default="",
        null=False,
        blank=False)

    featured = models.BooleanField(
        default=False)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode class."""
        return str(self.category_name)


class SubCategoryParent(models.Model):
    """docstring for ClassName."""

    category = models.ForeignKey(
        Category,
        null=True,
        blank=True)

    sub_cat_parent_name = models.CharField(
        max_length=120,
        null=True,
        blank=True)

    description = models.TextField(
        null=True,
        blank=True)

    slug = models.SlugField(
        unique=True,
        default="",
        null=False,
        blank=False)

    featured = models.BooleanField(
        default=False)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode class."""
        return str(self.sub_cat_parent_name)


class SubCategoryChild(models.Model):
    """docstring for ClassName."""

    sub_category_parent = models.ForeignKey(
        SubCategoryParent,
        null=True,
        blank=True)

    sub_cat_child_name = models.CharField(
        max_length=120,
        null=True,
        blank=True)

    description = models.TextField(
        null=True,
        blank=True)

    slug = models.SlugField(
        unique=True,
        default="",
        null=False,
        blank=False)

    featured = models.BooleanField(
        default=False)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode class."""
        return str(self.sub_cat_child_name)


class Brand(models.Model):
    """docstring for ClassName."""

    brand_name = models.CharField(
        max_length=120,
        null=True,
        blank=True)

    description = models.TextField(
        null=True,
        blank=True)

    slug = models.SlugField(
        unique=True,
        default="",
        null=False,
        blank=False)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    featured = models.BooleanField(
        default=False)

    active = models.BooleanField(
        default=True)

    def __unicode__(self):
        """Unicode class."""
        return str(self.brand_name)


class BrandConfiguration(models.Model):
    """Brand Config."""

    brand = models.ForeignKey(
        Brand,
        null=True,
        blank=True)

    sub_category_parent = models.ForeignKey(
        SubCategoryParent,
        null=True,
        blank=True)

    featured = models.BooleanField(
        default=False)

    order = models.IntegerField(
        blank=True,
        null=True)

    def __unicode__(self):
        """Unicode class."""
        return str(self.brand.brand_name)


class Product(models.Model):
    """Product class."""

    category = models.ForeignKey(
        Category,
        default="",
        null=False,
        blank=False)

    sub_category_parent = models.ForeignKey(
        SubCategoryParent,
        default="",
        null=False,
        blank=False)

    sub_category_child = models.ForeignKey(
        SubCategoryChild,
        default="",
        null=False,
        blank=False)

    brand = models.ForeignKey(
        Brand,
        default="",
        null=False,
        blank=False)

    title = models.CharField(
        max_length=120,
        null=False,
        blank=False)  # blank field means required field, null is for empty value.

    image = models.ImageField(
        upload_to='products/images',
        default="",
        blank=False,
        null=False)

    # description = models.TextField(
    #     null=True,
    #     blank=True)

    # price = models.DecimalField(
    #     decimal_places=2,
    #     max_digits=100,
    #     default=0.0)

    # sale_price = models.DecimalField(
    #     decimal_places=2,
    #     max_digits=100,
    #     null=True,
    #     blank=True)

    slug = models.SlugField(
        unique=True)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    active = models.BooleanField(
        default=True)

    # update_defaults = models.BooleanField(
    #     default=False)

    def __unicode__(self):
        """Unicode class."""
        return self.title

    class Meta:
        unique_together = ('title', 'slug')

    def get_price(self):
        """Some method."""
        return self.price

    # def get_absolute_url(self):
    #     return reverse("single_product", kwargs={"slug": self.slug})


class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(active=True)

    # def storage(self):
    #     return self.all().filter(category='storage')

    # def colors(self):
    #     return self.all().filter(category='color')

    # def screen_size(self):
    #     return self.all().filter(category='screen_size')


# VAR_CATEGORIES_COLOR = (
#     ('storage', 'storage'),
#     ('color', 'color'),
#     ('screen_size', 'screen_size'))

# VAR_CATEGORIES_STORAGE = (
#     ('storage', 'storage'),
#     ('color', 'color'),
#     ('screen_size', 'screen_size'))

# VAR_CATEGORIES_SCREEN_SIZE = (
#     ('storage', 'storage'),
#     ('color', 'color'),
#     ('screen_size', 'screen_size'))


class Variation(models.Model):
    product = models.ForeignKey(
        Product)

    color = models.CharField(
        max_length=120,
        # choices=VAR_CATEGORIES,
        null=True,
        blank=True)

    storage = models.CharField(
        max_length=120,
        # choices=VAR_CATEGORIES,
        null=True,
        blank=True)

    screen_size = models.CharField(
        max_length=120,
        # choices=VAR_CATEGORIES,
        null=True,
        blank=True)

    quantity = models.IntegerField(
        null=True,
        blank=True)

    price = models.DecimalField(
        decimal_places=2,
        max_digits=100,
        null=True,
        blank=True)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    active = models.BooleanField(
        default=True)

    objects = VariationManager()

    def __unicode__(self):
        return "%s, %s, %s" % (self.storage, self.color, self.screen_size)


class ProductImage(models.Model):
    """Product Image Class."""

    variation = models.ForeignKey(
        Variation,
        null=True,
        blank=True)

    image = models.ImageField(
        upload_to='Variation/images')

    # featured = models.BooleanField(
    #     default=False)

    thumbnail = models.BooleanField(
        default=False)

    active = models.BooleanField(
        default=True)

    timestamp = models.DateTimeField(
        auto_now_add=True,
        auto_now=False)

    updated = models.DateTimeField(
        auto_now_add=False,
        auto_now=True)

    def __unicode__(self):
        """Unicode Class."""
        return str(self.variation)

# def product_defaults(sender, instance, created, *args, **kwargs):
#     import ipdb; ipdb.set_trace()
#     if instance.update_defaults:
#         categories = instance.category.all()
#         print categories
#         for cat in categories:
#             print cat.id
#             if cat.id == 1: #for t-shirts
#                 small_size = Variation.objects.get_or_create(product=instance, 
#                                             category='size', 
#                                             title='Small')
#                 medium_size = Variation.objects.get_or_create(product=instance, 
#                                             category='size', 
#                                             title='Medium')
#                 large_size = Variation.objects.get_or_create(product=instance, 
#                                             category='size', 
#                                             title='Large')
#         instance.update_defaults = False
#         instance.save()
#     #print args, kwargs

# post_save.connect(product_defaults, sender=Product)

ecommerce/templates/products/results.html
{% extends "base.html" %}
{% load staticfiles products_custom_filter %}


{% block content%}




<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Searched for: {{ query }}</h3>
		</div>
		<div class="col-md-4">

		</div>
	</div>

	<div class="row">
	{% for product in products %}
	{% for variation in product.variation_set.all %}

		<div class="item col-md-4 col-sm-6 col-xs-12 row" style="margin: 20px 20px 20px 20px; background-color: #fff; width: 275px; height: 335px;">
		    
		    
		      
		      <div style="/*height: 235px;8? padding: 0px 0px 0px 0px; margin: 10px 10px 10px 10px;">
		        <a href='{% url "single_product" variation.product.slug variation.id %}'>
		          {% for img in  variation.productimage_set.all|filter_product_images:variation.product %}
		            <img class="img-responsive" style="width: auto; height: auto; max-width: 160px; max-height: 170px; display: block; margin-left: auto; margin-right: auto;" src='{{ MEDIA_URL }}{{ img.image }}'/>
		          {% endfor %}
		        </a>
		      </div>

		      <div class="col-md-12">
		        <a href='{% url "single_product" variation.product.slug variation.id %}'><p class="col-md-12">{{ variation.product.title }} - {{ variation.storage }}, {{ variation.color }}</p></a>
		      </div>

		    
	  	</div>

	{% endfor %}    
	{% endfor %}
	</div>
</div>


{% endblock %}

ecommerce/templates/products/single.html
{% extends "base.html" %}
{% load staticfiles products_custom_filter %}
<div class="page-header">
	
</div>

{% block content%}



<div class="container data-wrapper" /*style="padding-left: 100px; padding-right: 110px;"*/ >
	

	<div class="row">
		<h3 class="col-md-6">{{ product.title }}</h3>
	</div>
	<div class="row">
		<p1 class="col-md-6">by  {{product.brand}}, {{product.sub_category_child}}</p1>

	</div><br>

	<div class="row" >

		<div class="col-md-7">

			<div class="col-md-12" style="width: 500px; background-color: #fff; box-shadow: 0 0 4px #d3cbb8; padding: 30px 30px 30px 30px;">
				<!--bootstarp carousel -->

				<div class="" style=''>
				    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

				      <!-- Wrapper for slides -->
				      <div class="carousel-inner" role="listbox" style="">
				    
				        {% for img in variation.productimage_set.all|filter_product_images_2:variation.product %}
					        
					          <div class="item {% if forloop.first %}active{% endif %}">
					          	<img class="img-responsive" style="max-height: 400px; display: block; margin-left: auto; margin-right: auto;" src="{{ MEDIA_URL }}{{ img }}">
					          </div>
					        
				        {% endfor %}
				      </div>
				    </div>
				    <div class="" style="margin-left: 17px; margin-top: 31px;">
					    {% for img in variation.productimage_set.all|filter_product_images_2:variation.product %}
				    		<span style="margin-right: 10px;">
						    <a class="" data-target="#carousel-example-generic" role="button" data-slide-to="{{ forloop.counter|add:"-1" }}">
							    <img src='{{ MEDIA_URL }}{{ img }}' style="width: 50px; height: 50px;">
							</a>
							</span>
						{% endfor %}
					</div>
				</div>
				<!-- carousel ends here -->
			</div>
		</div>

		


		<div class="col-md-5" style="background-color: #fff; box-shadow: 0 0 4px #d3cbb8; width: 474px; padding-bottom: 30px;">

			<div class="col-md-6">
				<h1 id="update-price"></h1>
				<p id="update-stock"></p>
				<!--<p>rs.12000</p>-->
			</div>

			<div class="col-md-6">
				<!--<p>you save rs.1000</p>-->
				
			</div>

			<div class="col-md-12">
			<form action="{% url 'get_product_variation_price' %}" id="product-variation-form">
				{% csrf_token %}
					<label>Variation</label><select name="variation" id="variant" class="form-control" id="sel1">
						
						<option id="{{variation.id}}" value="{{variation.id}}">{% if variation.color %}{{variation.color}}{% endif %}{% if variation.storage %}, {{variation.storage}}{% endif %}{% if variation.screen_size %}, {{variation.screen_size}}{% endif %}</option>
						
						{% for variant in variations %}
							{% if variant.id != variation.id %}
								<option id="{{variant.id}}" value="{% url "single_product" variant.product.slug variant.id %}">{% if variant.color %}{{variant.color}}{% endif %}{% if variant.storage %}, {{variant.storage}}{% endif %}{% if variant.screen_size %}, {{variant.screen_size}}{% endif %}</option>
							{% endif %}
						{% endfor %}
					</select>
			</form>
			</div>

			<div class="col-md-12">
				<form method='POST' action='{% url "add_to_cart" product.slug  %}'>{% csrf_token %}
					<label>Quantity</label><input class='form-control' name="qty" type="number" value='1'>
					<br>
					<select class='form-control' name='variation-form' id="variation-form-id" style="display: none;">
						<option id="option-1" value='' selected></option>
					</select>
					
					<input id="add-to-cart" class='btn btn-success btn-block' type='submit' disabled value='Add to cart'>
					<br>

					
				</form>

				<form id="wishList" action='{% url "add_wish_list" %}'>{% csrf_token %}
					<input class="btn btn-default btn-block glyphicon glyphicon-heart AddWishList" id="" onclick="this.blur();" value="Add to Wishlist">
				</form>

				<div class="alert alert-success fade in MsgWishList" style="display: none; position: fixed; top: 143px;">
					<a href="#" class="close" style="padding-left: 14px;" data-dismiss="alert" aria-label="close">&times;</a>
					<strong id="MsgWishList"></strong>
				</div>
				
			</div>



		</div>

	</div>

	<img id="loader" src="{% static 'img/loader.gif' %}" style="position: absolute; margin: -325px 873px; display: none;" />

	<div style="margin-bottom: 50px;">

		{% if popular_products.count > 0 %}
		<h3>Popular Products</h3>
		<div class="multiple-items">
		  {% for variations in popular_products|filter_popular_products %}
  			{% for variation in variations %}
		      <div class="item thumbnail" style="padding: 20px 20px 20px 20px; max-height: 450px; min-height: 350px;">
		        <a href='{% url "single_product" variation.product.slug variation.id %}' style="text-decoration: none; color: black;">
		          
		          
		          	{% for img in variation.product.productimage_set.all|filter_product_images:variation.product %}
		            	<img class="img-responsive" style="height: 200px; background-size: cover; background-repeat: no-repeat; background-position: center;" src='{{ MEDIA_URL }}{{ variation|get_thumbnail_img }}'>
		          	{% endfor %}
		     		
		     		<br>
		            <h6 style="text-align: center;">{{ variation.product.title|truncatechars:60 }} - {{ variation.storage }}, {{ variation.color }}</h6>
		            <h5 style="text-align: center;">Rs.<strong> {{ variation.price }}</strong></h5>
		          

		        </a>
		      </div>
		  {% endfor %}
		  {% endfor %}
		</div>
		{% endif %}


		<h3 class="uppercase">PRODUCT INFORMATION</h3>
		<div class="" style="background-color: #fff; box-shadow: 0 0 4px #d3cbb8;">
			<div class="row" style="margin-left: 10px;">
				{% if variation.pdpspecification_set.all %}<h4>SPECIFICATIONS</h4>{% endif %}
				{% for item in variation.pdpspecification_set.all %}
					{% if forloop.counter <= 4%}
					{% if item.active %}
						<p class="col-md-3" style="float: left;">{{item.specification_type}}</p> <p class="col-md-9">{{item.specification_value}}</p>
					{% endif %}
					{% endif %}
				{% endfor %}

				
				<div id="demo" class="collapse">
					{% for item in variation.pdpspecification_set.all %}
						{% if forloop.counter > 4%}
						{% if item.active %}
				    		<p class="col-md-3" style="float: left;">{{item.specification_type}}</p> <p class="col-md-9">{{item.specification_value}}</p>
			    		{% endif %}
			    		{% endif %}
		    		{% endfor %}
		  		</div>
		  		<a style="margin-left: 15px;" data-toggle="collapse" data-target="#demo">Read More</a>
				<hr>

		  		{% if variation.pdpdescription_set.all %}<h4>DESCRIPTION</h4>{% endif %}
		  		{% for item in variation.pdpdescription_set.all %}
		  			{% if item.active %}
						<p class="col-md-12" style="">{{item.description}}</p>
						<hr>
					{% endif %}
				{% endfor %}
				
				{% if variation.pdpphysicalfeature_set.all %}<h4>PHYSICAL FEATURES</h4>{% endif %}
		  		{% for item in variation.pdpphysicalfeature_set.all %}
		  			{% if item.active %}
		  				<img src="{{ MEDIA_URL }}{{item.key_feature_image}}">
					{% endif %}
				{% endfor %}
				<hr>

				{% if variation.pdpkeyfeature_set.all %}<h4>KEY FEATURES</h4>{% endif %}
		  		<div class="row">
		  			{% for item in variation.pdpkeyfeature_set.all %}
					
						{% if item.active %}
							<div class="col-md-4">
								{% if item.icon_type == "Google" and item.icon_class != None %}<i class="material-icons" style="float: left;">{{item.icon_class}}</i>{% endif %}<p style=""><span class="{% if item.icon_type == "Font-Awesome" %}{{item.icon_class}}{% endif %}"></span> {{item.title}}</p>
							</div>
						{% endif %}
					{% endfor %}
				</div>
				<hr>
				
				

		  		{% for item in variation.pdpfeatured_set.all|sort %}
		  			{% if forloop.counter|divisibleby:2 %}
		  			{% if item.active %}
		  				<div class="row">
		  					<div class="col-md-6">
		  						<h4 style="">{{item.header}}</h4>
								<p class="col-md-12" style="">{{item.description}}</p>
		  					</div>
		  					<div class="col-md-6">
		  						<img class="img-responsive row" src="{{ MEDIA_URL }}{{item.featured_image}}">
		  					</div>
		  				</div>
		  				<br>
		  				<br>
					{% endif %}
					{% else %}
					{% if item.active %}
		  				<div class="row">
		  					<div class="col-md-6">
		  						<img class="img-responsive" src="{{ MEDIA_URL }}{{item.featured_image}}">
		  					</div>
		  					<div class="col-md-6">
		  						<h4 style="">{{item.header}}</h4>
								<p class="col-md-12" style="">{{item.description}}</p>
		  					</div>
		  				</div>
		  				<br>
		  				<br>
					{% endif %}
					{% endif %}

				{% endfor %}

			</div>


			
		</div>
	</div>


</div>
<script type="text/javascript" src="{% static 'js/single.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}"/>

<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
{% endblock %}